//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioPlaybackAgent {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FMresx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FMresx() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AudioPlaybackAgent.FMresx", typeof(FMresx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentChannel.dat 的本地化字符串。
        /// </summary>
        internal static string CurrentChannel {
            get {
                return ResourceManager.GetString("CurrentChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentSong.dat 的本地化字符串。
        /// </summary>
        internal static string CurrentSong {
            get {
                return ResourceManager.GetString("CurrentSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentUser.dat 的本地化字符串。
        /// </summary>
        internal static string CurrentUser {
            get {
                return ResourceManager.GetString("CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://douban.fm/j/mine/playlist?from=mainsite&amp;channel=0&amp;kbps=128&amp;type=n 的本地化字符串。
        /// </summary>
        internal static string GetSongURL {
            get {
                return ResourceManager.GetString("GetSongURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SongPictureStrategy.dat 的本地化字符串。
        /// </summary>
        internal static string SongPictureStrategy {
            get {
                return ResourceManager.GetString("SongPictureStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SongPlayList.dat 的本地化字符串。
        /// </summary>
        internal static string SongPlayList {
            get {
                return ResourceManager.GetString("SongPlayList", resourceCulture);
            }
        }
    }
}
